package Enums;

public enum Escolaridade {
    ANALFABETO,
    FUNDAMENTAL_INCOMPLETO_1A4,
    FUNDAMENTAL_COMPLETO_4A,
    FUNDAMENTAL_INCOMPLETO_5A8,
    FUNDAMENTAL_COMPLETO,
    MEDIO_INCOMPLETO,
    MEDIO_COMPLETO,
    SUPERIOR_INCOMPLETO,
    SUPERIOR_COMPLETO,
    IGNORADO,
    NAO_SE_APLICA
}
